updated README file
saphetor/varsome-api-client-python pull request #25
Opened 2024-03-14 08:45 UTC by thasteris

2024-03-14 09:06 UTC, kchatzikok requested changes

2024-03-14 09:06 UTC, kchatzikok commented on README.md
> +    varsome_api_run.py -g hg19 -k 'api-key' -u https://stable-api.varsome.com -q 'single-read/AGTCCRAGTTGTAAATGGTACACTCGGCGTAAGCCTGAAAAGATAAAATCAAAGATGTAAAGGTGAGCACAGTCTAAGTTCTCTCTGAAGTGTCAATGGGAATGC
Change this to the following:
```
Try the following to retrieve data relevant to a single read:
varsome_api_run.py -g hg19 -k api-key -q 'single-read/AGTCCRAGTTGTAAATGGTACACTCGGCGTAAGCCTGAAAAGATAAAATCAAAGATGTAAAGGTGAGCACAGTCTAAGTTCTCTCTGAAGTGTCAATGGGAATGCAGATTGGATTAAATAAATGCTGCCCAAGTGCATACTCAAAGAGGC' -p add-all-data=1
```

2024-03-14 09:06 UTC, kchatzikok commented on README.md
> +To view available request parameters (used by the 'params' method parameter), refer to an example at api.varsome.com.
remove this text

2024-03-14 09:06 UTC, kchatzikok commented on README.md
> +To view available request parameters (used by the 'params' method parameter), refer to an example at api.varsome.com.
Please change this to the following
```
Try the following query to retrieve transcript-related data:
varsome_api_run.py -g hg19 -k api-key -q 'transcript/NM_001276760' -p add-all-data=1
```

2024-03-14 10:20 UTC, thasteris commented
@kchatzikok , thank you for your detailed comments. I made the changes.

2024-03-20 11:27 UTC, bsantor approved these changes

2024-03-20 12:19 UTC, n-zervos approved these changes

2024-03-26 07:17 UTC, kchatzikok requested changes

2024-03-26 07:17 UTC, kchatzikok commented on README.md
> +    varsome_api_run.py -g hg19 -k api-key -q https://stable-api.varsome.com -q 'cnv/chr2:83300000:106000000:dup' -p add-all-data=1
It should be without the stable-api
```python
varsome_api_run.py -g hg19 -k api-key -q 'cnv/chr2:83300000:106000000:dup' -p add-all-data=1
```

2024-03-26 07:17 UTC, kchatzikok commented on README.md
> +    varsome_api_run.py -g hg19 -k api-key -q https://stable-api.varsome.com -q 'gene/EGFR' -p add-all-data=1
```python
varsome_api_run.py -g hg19 -k api-key -q 'gene/EGFR' -p add-all-data=1
```

2024-03-26 09:27 UTC, thasteris commented on README.md
> +    varsome_api_run.py -g hg19 -k api-key -q https://stable-api.varsome.com -q 'gene/EGFR' -p add-all-data=1
Done 👍🏼  @kchatzikok !!!

2024-03-26 09:40 UTC, kchatzikok approved these changes

2024-03-26 09:40 UTC, merged